### ISSUE TITLE
NPM version way out of date

### ISSUE THREAD

**Issue by tivac** [porsager/wright#12]
Is wright not being published to npm currently? NPM version is at `0.1.0` but this repo's package.json says `0.6.1`, curious as to why it isn't getting updated.

I ran into this while trying to use wright for the first time and having it all explode spectacularly :(

**Comment by porsager** [comment]
No, not yet, I just took the name back then and wanted to wait with publishing until I felt wright was stable (or the api was stable at least).

I should probably not have written `npm install` examples in the README :P

I hope to get it published soon though.

**Comment by porsager** [comment]
So, there's still some things I'm not satisfied with, but not publishing to npm just because of that started to become silly.. 

It's now published as 0.7.0, and I'll just need to update the different readme's with instructions etc.
