### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by cmnstmntmn** [porsager/wright#18]
i noticed that i'm running out of CPU soon after wright is started.

![screen shot 2017-03-02 at 00 06 42](https://cloud.githubusercontent.com/assets/2312755/23483568/2c426c0c-fedc-11e6-9282-378efc5cfe81.png)

**Comment by porsager** [comment]
Interesting. 

Could you post the output of setting debug to 1? Either `-d 1` in the console or `debug: 1` in js? 

Thanks

**Comment by cmnstmntmn** [comment]
```js
Starting wright...
Debug: { name: 'ui-kit',
  main: 'index.html',
  run: 'm.redraw',
  serve: '/Users/constantin/Sites/ui-kit',
  execute: [],
  watch: [ '**/*.html' ],
  js: 
   [ { watch: 'src/**/*.js',
       path: '/dist/app.js',
       compile: [Function: roll] } ],
  css: 
   [ { watch: 'src/css/**/*.css',
       compile: [Function: style],
       path: '/dist/app.css' } ],
  port: 3018,
  jail: true,
  debug: 1,
  fps: false,
  clone: false,
  set: [Function],
  id: 'Sites-ui-kit_88945a1',
  external: false,
  appData: '/Users/constantin/Library/Application Support/wright/Sites-ui-kit_88945a1',
  url: 'http://localhost:3018/',
  debugPort: 3019,
  debugProxyPort: 3020,
  debugUrl: 'http://localhost:3019' }
```

**Comment by porsager** [comment]
@cmnstmntmn I noticed that in the screenshot the node process has 3 hours and 35 minutes cpu time, which indicates it's been running for quite some time. Are you sure that node process was launched by wright? Can you replicate this easily?

**Comment by cmnstmntmn** [comment]
well, it's easy to replicate (in my case) is happening every time i'm running wright.
i'll come with some extra details later today.

i'm wondering if some subprocesses are responsible for this issue;
`rollup`, `postcss` that i'm using

**Comment by porsager** [comment]
There might be a watch in one of those running recursively? If it's something you can share could you put it in a gist?

**Comment by cmnstmntmn** [comment]
here's the [config/plugins](https://gist.github.com/cmnstmntmn/9147e6b416c1462f0ff067992260bd13) that i'm using

**Comment by porsager** [comment]
Files loaded in the browser needs to have a match inside the served folder.

When `serve` is not specified directly it will default to the current working directory or the base directory of the path in `main`. 

In this case the solution was to either set `serve: 'dist'` or move `index.html` to `dist` and set main to `main: 'dist/index.html'`

I'll try to see if I can somehow make a better warning if wright tries to watch too many missing files..
