### ISSUE TITLE
No async/await support?

### ISSUE THREAD

**Issue by ForsakenHarmony** [porsager/wright#22]
wright doesn't seem to like async/await, crashing on the first line of an async function:

```
Error: Error jailing:
Error: Line 96: Unexpected token function
Error:   let then;
Error: Column: 2001
```

**Comment by porsager** [comment]
I just pushed a new update with the newer esprima and astring versions that should fully support ES2016.

It should work if you update now ;)

**Comment by ForsakenHarmony** [comment]
Cool, I'll try it tomorrow

**Comment by porsager** [comment]
I did a couple of tests myself and checked this works, so I'll close this issue, but let me know if you bump into anything ;)
