### ISSUE TITLE
throw error when watch

### ISSUE THREAD

**Issue by futurist** [porsager/wright#31]
I don't know why throw below error when sometime of watch running:
```
20:48:26.636 Debug: Reloading dist/service-worker.js
Assertion failed: (0), function uv_close, file ../deps/uv/src/unix/core.c, line 182.
/bin/sh: line 1:  3569 Abort trap: 6
```

any idea?

**Comment by porsager** [comment]
That seems like a very deep error.. Have you experienced this recently?

Oh, and apologies for the late reply, this issue had completely slipped under my radar..

**Comment by porsager** [comment]
@futurist I'm going to close this out, but feel free to open if you are still experiencing errors with `wright@next`
