### ISSUE TITLE
Multiple serve directories

### ISSUE THREAD

**Issue by spacejack** [porsager/wright#34]
Would be great to allow multiple serve paths when used in conjunction with a web server like express when you're serving more than one static directory. Eg in this case:

```javascript
app.use('/', express.static('public'))
app.use('/foo', express.static('/some/other/path'))
```

**Comment by porsager** [comment]
@spacejack you can try out wright@next and use the `-a` `--assets` options multiple times for serving more directories...

**Comment by porsager** [comment]
This will be in 2.0 - If you find issue with it then, let me know ;)
