### ISSUE TITLE
Meteor

### ISSUE THREAD

**Issue by yorrd** [porsager/wright#35]
Hi! I'd love to use this library with Meteor. Meteor includes a build system (isobuild) which rocks. The short story is: it gives its compiler plugins only a list of files that it needs to compile and wants the compiled output back from the plugin. Also, it serves its contents on its own

So if I were to write a Meteor plugin for wright, which I would absolutely love to do, I'm assuming wright would need some changes?

Are you aware of Meteor? If not, I'd be glad to give you a boiled-down version of what's needed to integrate with the Meteor build system and we can check if a pull request is something that you'd be open to.

Thanks for the wright project :smiley:

**Comment by porsager** [comment]
Hi @yorrd ... That sounds very interesting.. I'm aware of Meteor, but it's been a few years since I've checked up on it.

I think there's a good chance you can hoop up isobuild with wright through the JS api. If you have a sample app setup that uses isobuild, I'd be happy to take a quick look and see if it would be straight forward.

**Comment by yorrd** [comment]
@porsager I'll make a simple sample repository and set up a package for Meteor that is supposed to implement wright. Let me get back to you asap!

Thanks for your support <3

**Comment by yorrd** [comment]
@porsager I've got a problem getting wright to run, maybe you can help me:

Meteor - in its package system - is able to compile down to the specified target (with the ecmascript plugin). However, it seems that your other package, `ubre`, while being served from the dist repository, has a `export ...` statement which Meteor then stumbles over. Do you need this statement? It seems like it's out of place without knowing your code.

Thanks!

**Comment by porsager** [comment]
It sounds like you're using wright in the wrong way if you're seeing an error like that.

You should let wright start meteor and act as a proxy for things to work properly.

Are you able to show me what you have now?

**Comment by yorrd** [comment]
@porsager things got busy, I didn't forget you. Repo is coming soon... trying to figure out the JS API of wright first

**Comment by porsager** [comment]
Oh I know how it is ;) Same here.. Let me know if you need any pointers ;)

**Comment by porsager** [comment]
Feel free to open this issue if you want to continue in the future ;)
