### ISSUE TITLE
All Ajax POST requests fail with 2.x releases

### ISSUE THREAD

**Issue by shofetim** [porsager/wright#41]
When using the 2.x releases (2.0.0-beta to 2.0.0-rc8) AJAX post requests stay in "pending" status indefinitely.

Minimal case to reproduce:
``` html
<html>
  <body>
    <button id="post">Click to test post</button>
    <script src="./test.js"></script>
  </body>
</html>
```

```js
document.getElementById("post").onclick = () => { fetch("./anything", {method: "post"}); }
```

```shell-script
wright index.html --debug 1
```

Results
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/744064/74614178-e4311e80-50d2-11ea-9a9c-3879c78e6697.png">

**Comment by porsager** [comment]
Sorry for the bad response time.

Great repro case! Fixed in 2.0.1
