### ISSUE TITLE
TypeError: The "chunk" argument must be of type string or an instance of Buffer. Received an instance of Object

### ISSUE THREAD

**Issue by mhwang08** [porsager/wright#44]
I've determined that this error has to do with the version of Chrome that is being used. Can you indicate what the latest version of Chrome that is compatible with wright is, or support later versions of Chrome?

**Comment by porsager** [comment]
I'm pretty sure this was a bug fixed here: https://github.com/porsager/wright/commit/70b453893c898d7a09934900255ce8f5b2a0b171

Sorry for the late reply, let me know if 2.0 works for you
